using System.Numerics;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Omu.Client.RulesSmite.UI;

/// <summary>
///     Window displaying the rules with a countdown until they can close it. Fuckrules won't save you this time.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class RulesSmiteWindow : FancyWindow
{
    [Dependency] private readonly IClyde _clyde = default!;

    /// <summary>
    ///     How much time is left until the window can be closed.
    /// </summary>
    private float _timeLeft;

    /// <summary>
    ///     Fired when the accept button is pressed to close the window.
    /// </summary>
    public event Action? OnAcceptPressed;

    public RulesSmiteWindow(float time)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _timeLeft = time;

        CloseButton.Visible = false; // Nuh uh!

        AcceptButton.OnPressed += _ => OnAcceptPressed?.Invoke();
    }

    protected override void Opened()
    {
        base.Opened();

        _clyde.OnWindowResized += OnWindowResized;
    }

    public override void Close()
    {
        if (!IsOpen)
            return;

        // You didn't say the magic word!
        if (_timeLeft > 0)
            return;

        _clyde.OnWindowResized -= OnWindowResized;

        base.Close();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        _timeLeft = Math.Max(0, _timeLeft - args.DeltaSeconds);
        Countdown.Text = Loc.GetString("ui-rulessmite-wait", ("time", MathF.Ceiling(_timeLeft)));

        if (_timeLeft == 0)
            AcceptButton.Disabled = false;
    }

    protected override void MouseMove(GUIMouseMoveEventArgs args)
    {
        Vector2 prevSize = SetSize;

        base.MouseMove(args);

        if (prevSize != SetSize)
            RecenterWindow(new Vector2(0.5f, 0.5f));
    }

    protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
    {
        var mode = base.GetDragModeFor(relativeMousePos);

        if (mode == DragMode.Move)
            mode = DragMode.None;

        return mode;
    }

    private void OnWindowResized(WindowResizedEventArgs args)
    {
        // If the game window was resized, we won't be in the center anymore. Fix that.
        RecenterWindow(new Vector2(0.5f, 0.5f));
    }
}
